const data = [
  {
    name: "Sam Altman",
    email: "sumal@gmail.com",
    level: "Medium",
    Action_reason: "Flagged",
    Time_to_close: "14 days",
    date: "12 Oct,2023",
    reviewed_By: "Neil",
    reviewed_email: "neil@onjuno.com",
    status: "completed",
  },
  {
    name: "Sameer Choubey",
    email: "sameerchoubey123@gmail.com",
    level: "High",
    Action_reason: "Closed",
    Time_to_close: "14 days",
    date: "12 Oct,2023",
    reviewed_By: "Pratik",
    reviewed_email: "pratik@onjuno.com",
    status: "completed",
  },
  {
    name: "Adarsh Panikkar",
    email: "adarsh@onjuno.com",
    level: "Low",
    Action_reason: "Cleared",
    Time_to_close: "15 days",
    date: "12 Oct,2023",
    reviewed_By: "Prashanth",
    reviewed_email: "prashanth@onjuno.com",
    status: "completed",
  },
  {
    name: "Pratik Shetty",
    email: "pratik3@gmail.com",
    level: "High",
    Action_reason: "SOI requested",
    Time_to_close: "15 days",
    date: "12 Oct,2023",
    reviewed_By: "Rasleen Kaur",
    reviewed_email: "rasleen@onjuno.com",
    status: "completed",
  },
  {
    name: "Elon Musk",
    email: "elon@twitterceo.com",
    level: "Low",
    Action_reason: "Flagged",
    Time_to_close: "15 days",
    date: "12 Oct,2023",
    reviewed_By: "Pratik Shetty",
    reviewed_email: "pratik@onjuno.com",
    status: "completed",
  },
  {
    name: "Trina Kundu",
    email: "trina@onjuno.com",
    level: "Low",
    Action_reason: "Closed",
    Time_to_close: "15 days",
    date: "12 Oct,2023",
    reviewed_By: "Varun Deshpande",
    reviewed_email: "varun@onjuno.com",
    status: "completed",
  },
  {
    name: "Sam Altman",
    email: "sumal@gmail.com",
    level: "Medium",
    Trigger_reason: "IP Change",
    In_queue: "4 days",
    date: "12 Oct,2023",
    Previously_reviewed: "Yes",
    reviewed_Date: "23 Aug, 2023",
    status: "pending",
  },
  {
    name: "Sameer Choubey",
    email: "sameerchoubey123@gmail.com",
    level: "High",
    Trigger_reason: "FIFO",
    In_queue: "4 days",
    date: "12 Oct,2023",
    reviewed_By: "Pratik",
    Previously_reviewed: "No",
    status: "pending",
  },
  {
    name: "Adarsh Panikkar",
    email: "adarsh@onjuno.com",
    level: "Low",
    Trigger_reason: "IP Change",
    In_queue: "5 days",
    date: "12 Oct,2023",
    reviewed_By: "Prashanth",
    Previously_reviewed: "No",
    status: "pending",
  },
  {
    name: "Pratik Shetty",
    email: "pratik3@gmail.com",
    level: "High",
    Trigger_reason: "FIFO",
    In_queue: "5 days",
    date: "12 Oct,2023",
    reviewed_By: "Rasleen Kaur",
    Previously_reviewed: "Yes",
    reviewed_Date: "23 Sep, 2023",
    status: "pending",
  },
  {
    name: "Elon Musk",
    email: "elon@twitterceo.com",
    level: "Low",
    Trigger_reason: "FIFO",
    In_queue: "5 days",
    date: "12 Oct,2023",
    reviewed_By: "Pratik Shetty",
    Previously_reviewed: "Yes",
    reviewed_Date: "23 Sep, 2023",
    status: "pending",
  },
  {
    name: "Trina Kundu",
    email: "trina@onjuno.com",
    level: "Low",
    Trigger_reason: "FIFO",
    In_queue: "5 days",
    date: "12 Oct,2023",
    reviewed_By: "Varun Deshpande",
    Previously_reviewed: "Yes",
    reviewed_Date: "23 Sep, 2023",
    status: "pending",
  },
];
export default data;
